# AMI looked up via data source, not hardcoded - the lesson's own
# "ami-0edab43b6fa892279" is a specific, already-stale AMI ID from us-west-1;
# this finds whatever Canonical's current Ubuntu 24.04 LTS build is, in
# whatever region the provider is pointed at.
data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"] # Canonical

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# Generated by Terraform itself, instead of requiring a pre-existing
# ~/.ssh/web.pub on whoever runs this - self-contained, and the private
# half is available as a (sensitive) output for a real SSH connection.
resource "tls_private_key" "web" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "web" {
  key_name   = "module-08-webserver-key"
  public_key = tls_private_key.web.public_key_openssh
}

resource "aws_security_group" "ssh_access" {
  name        = "module-08-ssh-access"
  description = "Allow SSH access from the Internet"
}

# Separate rule resources, not inline ingress/egress blocks on the security
# group itself - the current AWS provider (v5+) recommendation, since each
# rule this way has its own ID and can be added/removed/tagged independently
# instead of forcing the whole security group to be re-evaluated as one blob.
resource "aws_vpc_security_group_ingress_rule" "ssh" {
  security_group_id = aws_security_group.ssh_access.id
  description       = "SSH - demo only, not a real-world rule"

  from_port   = 22
  to_port     = 22
  ip_protocol = "tcp"
  cidr_ipv4   = "0.0.0.0/0"
}

resource "aws_vpc_security_group_egress_rule" "all" {
  security_group_id = aws_security_group.ssh_access.id
  description       = "All outbound - needed for apt update/install in user_data"

  ip_protocol = "-1"
  cidr_ipv4   = "0.0.0.0/0"
}

resource "aws_instance" "webserver" {
  ami                    = data.aws_ami.ubuntu.id
  instance_type          = "t3.micro" # current-generation, not the lesson's t2.micro - see 8.1
  key_name               = aws_key_pair.web.key_name
  vpc_security_group_ids = [aws_security_group.ssh_access.id]

  user_data = <<-EOF
    #!/bin/bash
    sudo apt update
    sudo apt install nginx -y
    systemctl enable nginx
    systemctl start nginx
  EOF

  tags = {
    Name        = "webserver"
    Description = "An Nginx WebServer on Ubuntu"
  }
}
